import SimpleThreeColumns from '@/components/Features'
import BouttonComponents from '@/components/boutton'
import StatChakra from '@/components/chakra'
import LargeWithLogoLeft from '@/components/footer'
import LargeWithAppLinksAndSocial from '@/components/footer'
import SplitScreen from '@/components/header'
import InputComponents from '@/components/input'
import WithSubnavigation from '@/components/navbar'
import CallToActionWithAnnotation from '@/components/template-chakra'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main >
        
      <WithSubnavigation/>

      <SplitScreen/>

      <SimpleThreeColumns/>

      <LargeWithLogoLeft/>

      </main>
    </>
  )
}
