import BouttonComponents from '@/components/boutton'
import StatChakra from '@/components/chakra'
import SplitScreen from '@/components/header'
import InputComponents from '@/components/input'
import CallToActionWithAnnotation from '@/components/template-chakra'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

      <SplitScreen/>

      </main>
    </>
  )
}
